### ISSUE TITLE
bug: setting value of parameter passed by value

### ISSUE THREAD

**Issue by imatiramisu** [momo5502/open-iw5#109]
# Problem

https://github.com/momo5502/open-iw5/blob/4df450f9c55bdedba86501f8f26af18eadea95ac/src/launcher/html/doc_host_ui_handler.cpp#L73-L77

The function parameter `pguidCmdGroup` is set to `nullptr` in the body of the function, but the value is never used after that.

# Solution

If `pguidCmdGroup` an out value, then the parameter needs to be a reference to a pointer, otherwise, it should be removed.

**Comment by diamante0018** [comment]
Fixed on master
