### ISSUE TITLE
more commands (SP)

### ISSUE THREAD

**Issue by Combine900** [momo5502/open-iw5#2]
May busy with other stuff and probably a dead project but could we have some basic console commands?

as this client is great it isnt laggy like the original steam version.

god - godmode
demigod - enable magic bulletshield function
notarget - makes you invisible too the ai
give xyz - give yourself any weapon. (think thats not possible)
noclip - enables flying and disable clipping

**Comment by Combine900** [comment]
any chance by getting updates again?

**Comment by momo5502** [comment]
All of these are possible

**Comment by Combine900** [comment]
Well i hope you may add this stuff, if so put a donation link for this project somewhere pls :=)

**Comment by mjkzy** [comment]
surprised these haven't been added already lol. I may make a pull request if I can get my hands on a IW5 db

**Comment by skkuull** [comment]
I might be doing that since its super ez to do, but i don't think i will be doing this for sp because i don't own the game on steam.

**Comment by mjkzy** [comment]
> I might be doing that since its super ez to do, but i don't think i will be doing this for sp because i don't own the game on steam.

you don't need to own the game. MW3 Dedicated Server works.

**Comment by skkuull** [comment]
yea, i was talking about singleplayer

**Comment by Combine900** [comment]
Any news?

**Comment by momo5502** [comment]
> I might be doing that since its super ez to do, but i don't think i will be doing this for sp because i don't own the game on steam.

You don't need to own the game, you can use the dedi files. That's literally the whole point of this project.

**Comment by diamante0018** [comment]
> Any news?

Soon:tm:
