### ISSUE TITLE
GSC loader: Error parsing include file

### ISSUE THREAD

**Issue by VladWinner** [momo5502/open-iw5#230]
I tried to load gsc from a single-player map using decompiled sources and copying [the desired file](https://drive.google.com/file/d/1zHHznn8zlXCU4qNdzEj2GCX97t8Px7pF/view?usp=share_link) `intro.gsc` to `/userraw/maps`, but this causes an error.
![image](https://user-images.githubusercontent.com/13555921/212550138-0ef3bdb0-a6a4-41cc-b647-383d702ce11a.png)
Is there any workaround to this issue?

**Comment by diamante0018** [comment]
you can only include gsc files that are in clear text.
do not use #include at the top if the script is in a fastfile.
use maps\_utility::func in your script

**Comment by diamante0018** [comment]
In the next update of gsc-tool this will be possible again. Don't have an ETA though.

**Comment by diamante0018** [comment]
Done
