### ISSUE TITLE
SP crash

### ISSUE THREAD

**Issue by Combine900** [momo5502/open-iw5#46]
Hey, noticed some problems loading a SP map while using "developer 1/2"

May the "unknown function" had something to do with removed "debug functions"?

https://www.youtube.com/watch?v=oiIfITHmla4

**Comment by diamante0018** [comment]
Can you try with `spdevmap`?
I am not too sure what is the difference but it seems that is indicated for this purpose. `devmap` is probably mean for the 'host' of SO not the campaign. Just me guessing thought

**Comment by diamante0018** [comment]
Okay, so I know why this is crashing. (even with `spdevmap`)
Basically, IW never intended for people to be able to set developer to 1.
They clearly partially failed to strip development features from the sp binary unlike from mp where they are gone completely.
When you try to run game script with developer set to 1 it will try to "Link" functions that were stripped from the game.
I don't think this can be fixed easily as the functions don't even have names but IDs and I don't think anyone wants to spend time figuring this one out😅

**Comment by momo5502** [comment]
Adding a missing script function is required. Figuring out the id should easily be doable when debbung. 
Something similar was already done in FourDeltaOne's IW5M source to support loading newer scripts with legacy binaries:
https://github.com/KANT0S/FourDeltaOne/blob/master/IW5M/iw5m/code/clientdll/PatchIW5DS.cpp#L214

**Comment by Combine900** [comment]
Okay, well ahm another question about the debug stuff was.. is it possible too "activate" the debug output informations as we got it in the other cods?

Like dev comments in the dev-console etc.. i dont know what the developers exactly removed from mw3 that this stuff no longer prints in the dev console if you enable developer 1/2.

**Comment by diamante0018** [comment]
All these things you are mentioning are removed before the game is shipped.

**Comment by diamante0018** [comment]
If I've done debugging on my end correctly the game fails to link the following file.
[_id_4EA1.txt](https://github.com/momo5502/open-iw5/files/9002047/_id_4EA1.txt)
It's long and I don't have the time to calculate manually to figure out which line it's failing to link.
Posting this here so people can already know which file to look at in the future.

**Comment by diamante0018** [comment]
![image](https://user-images.githubusercontent.com/37080671/205448516-86d72274-a818-44d1-a006-93860612e329.png)

**Comment by diamante0018** [comment]
Do not load the fastfile directly, i believe by doing `map berlin` you are skipping something important.
Just select the mission from the menu and it will work fine.
I believe the mission is split in two main parts (flash-foward then flash-back), causing the script link error.

**Comment by VladWinner** [comment]
@Combine900 just use `devmap sp_berlin` instead of `devmap berlin`
